### ISSUE TITLE
Pre-trained models

### ISSUE THREAD

**Issue by sirfoga** [SamuelJoutard/DrivingPointsPredictionMIR#1]
Thanks for your contribution, we found it very interesting and motivating! We were thinking of using it for our current task: abdominal organ registration in the wild. Can you provide us the checkpoints (model weights) of your trained models?

**Comment by SamuelJoutard** [comment]
Hi,

thank you for your nice comment!

Here are the pre-trained weights:
https://drive.google.com/drive/folders/1Im5QL5-9BiloiSRD7w4j1ok1ZXytESas?usp=sharing

Let me know if you have issues accessing them or loading the models. I am closing the issue for now.
